### ISSUE TITLE
Ошибка создания сенсора

### ISSUE THREAD

**Issue by bastshoes** [alryaz/hass-lkcomu-interrao#11]
После последнего обновления (0.0.19) возникает следующая ошибка:

Source: custom_components/lkcomu_interrao/sensor.py:585
Traceback (most recent call last):
  File "/config/custom_components/lkcomu_interrao/_base.py", line 294, in _wrap_update_task
    return await update_task
  File "/config/custom_components/lkcomu_interrao/sensor.py", line 585, in async_refresh_accounts
    meters = await account.async_get_meters()
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 328, in async_get_meters
    return await self.async_get_smorodina_meters()
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 316, in async_get_smorodina_meters
    response = await AbonentEquipment.async_request(self.api, proxy, provider)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 327, in async_request
    return await api.async_action_map(cls, ACTION_SQL, proxy, data)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 594, in async_action_map
    data=list(map(map_with.from_response, filter(bool, response["data"]))),
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "<attrs generated init inter_rao_energosbyt.actions.sql.abonent.AbonentEquipment>", line 24, in __init__
    _setattr('vl_tarif', __attr_converter_vl_tarif(vl_tarif))
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by alryaz** [comment]
Напишите, пожалуйста, в Telegram: @alryaz

Имеются какие-то изменения в возвращаемых данных, которые выявились у Вас; попробуем выяснить, в чём дело.

**Comment by alryaz** [comment]
Исправлено в v0.0.20
