### ISSUE TITLE
Ошибка после обновления ХА до 2021.9.х

### ISSUE THREAD

**Issue by bastshoes** [alryaz/hass-lkcomu-interrao#14]
После обновления ХА до крайней версии возникает ошибка при запуске интеграции:
```
2021-09-09 11:24:22 ERROR (MainThread) [custom_components.lkcomu_interrao._base] Error occurred during task execution: TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'")

2021-09-09T08:24:22.684460911Z Traceback (most recent call last):

2021-09-09T08:24:22.684474397Z   File "/config/custom_components/lkcomu_interrao/_base.py", line 294, in _wrap_update_task

2021-09-09T08:24:22.684487170Z     return await update_task

2021-09-09T08:24:22.684499066Z   File "/config/custom_components/lkcomu_interrao/sensor.py", line 585, in async_refresh_accounts

2021-09-09T08:24:22.684511298Z     meters = await account.async_get_meters()

2021-09-09T08:24:22.684522562Z   File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 330, in async_get_meters

2021-09-09T08:24:22.684534860Z     return await self.async_get_smorodina_meters()

2021-09-09T08:24:22.684546614Z   File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 318, in async_get_smorodina_meters

2021-09-09T08:24:22.684558929Z     response = await AbonentEquipment.async_request(self.api, proxy, provider)

2021-09-09T08:24:22.684570694Z   File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 327, in async_request

2021-09-09T08:24:22.684582949Z     return await api.async_action_map(cls, ACTION_SQL, proxy, data)

2021-09-09T08:24:22.684594617Z   File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 594, in async_action_map

2021-09-09T08:24:22.684606951Z     data=list(map(map_with.from_response, filter(bool, response["data"]))),

2021-09-09T08:24:22.684618765Z   File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response

2021-09-09T08:24:22.684661746Z     return cls(**init_args)  # type: ignore[call-arg]

2021-09-09T08:24:22.684675724Z   File "<attrs generated init inter_rao_energosbyt.actions.sql.abonent.AbonentEquipment>", line 9, in __init__

2021-09-09T08:24:22.684688611Z     _setattr('id_indication', __attr_converter_id_indication(id_indication))

2021-09-09T08:24:22.684700402Z TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Не доступен счетчик электричества Мособлэнерго.

**Comment by alryaz** [comment]
Тут скорее обновление со стороны Мосэнерго. Ожидайте исправления, будет сегодня.

**Comment by alryaz** [comment]
Исправлено в последнем релизе (v0.0.21)
