### ISSUE TITLE
Ошибка интеграции на HA 2021.11b0

### ISSUE THREAD

**Issue by avbor** [alryaz/hass-lkcomu-interrao#16]
В бета версии HA 2021.11 интеграция не работает, в логе ХА ошибка:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/lkcomu_interrao/sensor.py:147
Integration: Inter RAO Personal Cabinet (Energosbyt) (documentation, issues)
First occurred: 7:17:14 PM (1 occurrences)
Last logged: 7:17:14 PM

Error setting up entry my.mosenergosbyt.ru (+70000000000) for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 128, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/lkcomu_interrao/sensor.py", line 147, in <module>
    persistent_notification.SCHEMA_SERVICE_CREATE,
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'SCHEMA_SERVICE_CREATE'
```

Может быть что-то нужно поправить, чтобы к релизу не было сюрприза? =)

**Comment by alryaz** [comment]
Поправил в коммите, но пришлось пожертвовать функционалом уведомлений (не событий).

Попробуйте установить ветку `main` (HACS -> Интеграции -> Три точки под Энергосбытом -> Reinstall -> галка Show beta versions -> Выбрать main -> Установить).

**Comment by avbor** [comment]
Вроде работает, спасибо! :)

**Comment by alryaz** [comment]
Исправлено в v0.1.0
