### ISSUE TITLE
Unknown error occured Башэлектросбыт

### ISSUE THREAD

**Issue by dmitry-ponamarev** [alryaz/hass-lkcomu-interrao#17]
При попытке добавить интеграцию для ЛК Башэлектросбыт выдает "Unknown error occurred"
В лог пишет:

`2021-11-02 12:20:37 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/lkcomu_interrao/config_flow.py", line 171, in async_step_user
    self._accounts = await api.async_update_accounts()
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 911, in async_update_accounts
    response = await LSList.async_request(self)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 125, in async_request
    return await api.async_action_map(cls, ACTION_SQL, query, data)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 597, in async_action_map
    data=list(map(map_with.from_response, filter(bool, response["data"]))),
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "", line 3, in __init__
    _setattr('data', __attr_converter_data(data))
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 103, in _converter__ls_list__data
    return LSListData.from_response(value)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
TypeError: __init__() missing 1 required keyword-only argument: 'kd_ls_owner_type'
`

![bashesk](https://user-images.githubusercontent.com/12205781/139804181-85478b33-1c83-4e84-bfcf-093b6cd13e36.jpg)

**Comment by alryaz** [comment]
Снова, видать, поменяли формат данных. Ожидайте, сегодня вечером проверю все тонкости, исправлю.

**Comment by Blacksli** [comment]
Тоже проблема с Башэлектросбыт 

Logger: aiohttp.server
Source: custom_components/lkcomu_interrao/config_flow.py:171
Integration: Личный кабинет Интер РАО (Энергосбыт) ([documentation](https://github.com/alryaz/hass-lkcomu-interrao), [issues](https://github.com/alryaz/hass-lkcomu-interrao/issues))
First occurred: 15:48:58 (2 occurrences)
Last logged: 15:49:19

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/lkcomu_interrao/config_flow.py", line 171, in async_step_user
    self._accounts = await api.async_update_accounts()
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 911, in async_update_accounts
    response = await LSList.async_request(self)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 125, in async_request
    return await api.async_action_map(cls, ACTION_SQL, query, data)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 597, in async_action_map
    data=list(map(map_with.from_response, filter(bool, response["data"]))),
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "<attrs generated init inter_rao_energosbyt.actions.sql.ls_management.LSList>", line 3, in __init__
    _setattr('data', __attr_converter_data(data))
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 103, in _converter__ls_list__data
    return LSListData.from_response(value)
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
TypeError: __init__() missing 1 required keyword-only argument: 'kd_ls_owner_type'

**Comment by ostap7474** [comment]
При попытке добавить интеграцию для ЛК Башэлектросбыт выдает "Unknown error occurred"

Logger: aiohttp.server
Source: custom_components/lkcomu_interrao/config_flow.py:171
Integration: Личный кабинет Интер РАО (Энергосбыт) ([documentation](https://github.com/alryaz/hass-lkcomu-interrao), [issues](https://github.com/alryaz/hass-lkcomu-interrao/issues))
First occurred: 09:59:39 (1 occurrences)
Last logged: 09:59:39

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 178, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/lkcomu_interrao/config_flow.py", line 171, in async_step_user
    self._accounts = await api.async_update_accounts()
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 911, in async_update_accounts
    response = await LSList.async_request(self)
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 125, in async_request
    return await api.async_action_map(cls, ACTION_SQL, query, data)
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 597, in async_action_map
    data=list(map(map_with.from_response, filter(bool, response["data"]))),
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "<attrs generated init inter_rao_energosbyt.actions.sql.ls_management.LSList>", line 3, in __init__
    _setattr('data', __attr_converter_data(data))
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 103, in _converter__ls_list__data
    return LSListData.from_response(value)
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
TypeError: LSListData.__init__() missing 1 required keyword-only argument: 'kd_ls_owner_type'

**Comment by Gazplem** [comment]
При попытке добавить интеграцию для ЛК Башэлектросбыт выдает "Unknown error occurred"
