### ISSUE TITLE
Ошибка подключения интеграции к серверу приложения 

### ISSUE THREAD

**Issue by DieMetRik** [alryaz/hass-lkcomu-interrao#22]
Logger: homeassistant.config_entries
Source: custom_components/lkcomu_interrao/__init__.py:272
Integration: Личный кабинет Интер РАО (Энергосбыт) ([documentation](https://github.com/alryaz/hass-lkcomu-interrao), [issues](https://github.com/alryaz/hass-lkcomu-interrao/issues))
First occurred: 06:30:47 (1 occurrences)
Last logged: 06:30:47

Error setting up entry my.mosenergosbyt.ru (sa...nov@...) for lkcomu_interrao
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('195.82.140.228', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lkcomu_interrao/__init__.py", line 272, in async_setup_entry
    await api_object.async_authenticate()
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 612, in async_authenticate
    async with self._session.get(self.AUTH_URL) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host my.mosenergosbyt.ru:443 ssl:default [Connect call failed ('195.82.140.228', 443)]

**Comment by frfstu** [comment]
Тоже самое!!! Как вариант ошибка DNS/DHCP (Подобная ситуация была ранее с интеграцией mos.ru).

Обмен пакетами с my.mosenergosbyt.ru [195.82.140.228] с 32 байтами данных:
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.

Статистика Ping для 195.82.140.228:
    Пакетов: отправлено = 4, получено = 0, потеряно = 4
    (100% потерь)

Логи выдают следующее:

Logger: homeassistant.config_entries
Source: custom_components/lkcomu_interrao/__init__.py:272
Integration: Личный кабинет Интер РАО (Энергосбыт) ([documentation](https://github.com/alryaz/hass-lkcomu-interrao), [issues](https://github.com/alryaz/hass-lkcomu-interrao/issues))
First occurred: 01:08:53 (1 occurrences)
Last logged: 01:08:53

Error setting up entry my.mosenergosbyt.ru (*****username****) for lkcomu_interrao
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('195.82.140.228', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lkcomu_interrao/__init__.py", line 272, in async_setup_entry
    await api_object.async_authenticate()
  File "/usr/local/lib/python3.9/site-packages/inter_rao_energosbyt/interfaces.py", line 612, in async_authenticate
    async with self._session.get(self.AUTH_URL) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host my.mosenergosbyt.ru:443 ssl:default [Connect call failed ('195.82.140.228', 443)]

**Comment by theskillz** [comment]
Думаю связано с тем, что там профилактические работы. Личный кабинет через браузер тоже не открывается.
https://mosenergosbyt.ru/individuals/news/uvazhaemye-klienty-0303/

**Comment by frfstu** [comment]
Сегодня ночью опять также проблема возникла, до этого работало неделю точно!

**Comment by frfstu** [comment]
> Думаю связано с тем, что там профилактические работы. Личный кабинет через браузер тоже не открывается. https://mosenergosbyt.ru/individuals/news/uvazhaemye-klienty-0303/

Думаю что это скорее связано с массовыми DDoS атаками, чем с профилактическими работами, поскольку аналогичная проблема возникала и с интеграцией mos.ru.

**Comment by frfstu** [comment]
Вы не думали что это может быть связано с тем, что у нас у половины страны(физ и юр лиц) в качестве dns серверов Гугл прописан?! А это далеко не самый лучший сервер имён!!! Для информации: За 1 год из 7353006 запросов к которому, пришло 5943135 ответов с баннерами общим "весом" 267 гигабайт!

**Comment by pervolianinen** [comment]
> Сегодня ночью опять также проблема возникла, до этого работало неделю точно! Logger: homeassistant.config_entries Source: custom_components/lkcomu_interrao/**init**.py:272 Integration: Личный кабинет Интер РАО (Энергосбыт) (documentation, issues) First occurred: 03:54:56 (1 occurrences) Last logged: 03:54:56
> 
> Connect call failed ('195.82.140.228', 443)
> 
> При этом никаких перебоев с доступом в Интернет у меня нет.
Вы опять придумываете заговор. Ну не работает ночью ЛК со 2 марта!
Внимание!
Проводятся профилактические работы и настройка оборудования, с 2 марта 2022 года доступ к сервисам АО «Мосэнергосбыт», в том числе Личный кабинет клиента физических и юридических лиц, а также платёжная система энергосбытовой компании может быть ограничен с 23:00 до 7:00.
Приносим извинения за временные неудобства.

**Comment by belenkiy-lab** [comment]
Было бы решением, если бы можно было настроить расписание обновление. Так как ночью Личный кабинет не доступен.
Возможно ли сделать для Мосэнерго - отключение проверки в течении ночных часов?

**Comment by Laric0** [comment]
весной 2022 года работало, да и в начале лета тоже не было проблем
а вот начиная с конца осени авторизация не проходит
при этом войти в браузере в ЛК я могу, а вот в НА сбой авторизации и всё тут :(
обновление на последнюю версию не помогло ((

**Comment by serg-zab** [comment]
> весной 2022 года работало, да и в начале лета тоже не было проблем а вот начиная с конца осени авторизация не проходит при этом войти в браузере в ЛК я могу, а вот в НА сбой авторизации и всё тут :( обновление на последнюю версию не помогло ((

А куда авторизация не проходит?

**Comment by serg-zab** [comment]
> > > весной 2022 года работало, да и в начале лета тоже не было проблем а вот начиная с конца осени авторизация не проходит при этом войти в браузере в ЛК я могу, а вот в НА сбой авторизации и всё тут :( обновление на последнюю версию не помогло ((
> > 
> > 
> > А куда авторизация не проходит?
> 
> а никуда а) вернулся домой, проверяю - интеграция сообщает о ошибке авторизации перезапуск и прочие танцы с бубнами не помог визуально выглядело так, что в НА прямо на карточке был текст о ошибке авторизации
> 
> б) удалил интеграцию, пытаюсь настроить заново, и после ввода логина/пароля получаю отлуп :(

У меня такое было. Я не помню почему, но я пытался добавить аккаунт Мособлеирц - не работало. А вот Мосэнергосбыт зашёл без проблем

**Comment by ostap7474** [comment]
Logger: homeassistant.config_entries
Source: custom_components/lkcomu_interrao/__init__.py:275
Integration: Личный кабинет Интер РАО (Энергосбыт) ([documentation](https://github.com/alryaz/hass-lkcomu-interrao), [issues](https://github.com/alryaz/hass-lkcomu-interrao/issues))
First occurred: 09:06:40 (1 occurrences)
Last logged: 09:06:40

Error setting up entry lkk.bashesk.ru (an...@...ru) for lkcomu_interrao
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lkcomu_interrao/__init__.py", line 275, in async_setup_entry
    accounts: Mapping[AccountID, "Account"] = await api_object.async_update_accounts(
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 911, in async_update_accounts
    response = await LSList.async_request(self)
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 125, in async_request
    return await api.async_action_map(cls, ACTION_SQL, query, data)
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 597, in async_action_map
    data=list(map(map_with.from_response, filter(bool, response["data"]))),
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "<attrs generated init inter_rao_energosbyt.actions.sql.ls_management.LSList>", line 3, in __init__
    _setattr('data', __attr_converter_data(data))
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/ls_management.py", line 103, in _converter__ls_list__data
    return LSListData.from_response(value)
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/__init__.py", line 182, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
TypeError: LSListData.__init__() missing 1 required keyword-only argument: 'kd_ls_owner_type'


Авторизация не проходит.

**Comment by Dep1911** [comment]
Подтверждаю аналогичную ошибку.

**Comment by and7ey** [comment]
Думаю, можно рассмотреть вариант отключения интеграции ночью. 
Штатными средствами этого, увы, не сделать. Но можно через 
1) доп интеграцию Spook - https://spook.boo/integrations
2) либо скриптом на python'e https://community.home-assistant.io/t/loop-over-list-in-a-script/406343/2
