### ISSUE TITLE
Error on device update!

### ISSUE THREAD

**Issue by Sashik259** [alryaz/hass-lkcomu-interrao#26]
Error on Device Update!
After Home Assistant Core update from 2022.9.7 to 2022.10.2
`2022-10-10 19:09:31.312 ERROR (MainThread) [custom_components.lkcomu_interrao._base] Error occurred during task execution: EnergosbytException('ActionRequest error', 300, 'connect timed out (<no description provided>)')
Traceback (most recent call last):
File "/config/custom_components/lkcomu_interrao/_base.py", line 257, in _wrap_update_task
return await update_task
File "/config/custom_components/lkcomu_interrao/sensor.py", line 549, in async_refresh_accounts
meters = await account.async_get_meters()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 330, in async_get_meters
return await self.async_get_smorodina_meters()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 318, in async_get_smorodina_meters
response = await AbonentEquipment.async_request(self.api, proxy, provider)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 327, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')
2022-10-10 19:09:35.916 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform lkcomu_interrao is taking over 10 seconds.
2022-10-10 19:09:40.281 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: binary_sensor.lkcomu_interrao
2022-10-10 19:09:41.776 ERROR (MainThread) [homeassistant.components.sensor] lkcomu_interrao: Error on device update!
Traceback (most recent call last):
File "/config/custom_components/lkcomu_interrao/_util.py", line 153, in with_auto_auth
return await async_getter(*args, **kwargs)
File "/config/custom_components/lkcomu_interrao/sensor.py", line 345, in async_update_internal
self._balance = await account.async_get_balance()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 590, in async_get_balance
response_balance = await AbonentCurrentBalance.async_request(self.api, proxy, provider)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 265, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/config/custom_components/lkcomu_interrao/_base.py", line 506, in async_update
await with_auto_auth(self._account.api, self.async_update_internal)
File "/config/custom_components/lkcomu_interrao/_util.py", line 156, in with_auto_auth
return await async_getter(*args, **kwargs)
File "/config/custom_components/lkcomu_interrao/sensor.py", line 345, in async_update_internal
self._balance = await account.async_get_balance()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 590, in async_get_balance
response_balance = await AbonentCurrentBalance.async_request(self.api, proxy, provider)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 265, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')
2022-10-10 19:09:41.791 ERROR (MainThread) [homeassistant.components.binary_sensor] lkcomu_interrao: Error on device update!
Traceback (most recent call last):
File "/config/custom_components/lkcomu_interrao/_util.py", line 153, in with_auto_auth
return await async_getter(*args, **kwargs)
File "/config/custom_components/lkcomu_interrao/binary_sensor.py", line 82, in async_update_internal
self._last_payment = await self._account.async_get_last_payment()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 1155, in async_get_last_payment
return await self._internal_async_find_dated_last(self.async_get_payments, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 140, in _internal_async_find_dated_last
all_items = await async_getter(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 164, in async_get_payments
return await self.async_get_smorodina_payments(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 149, in async_get_smorodina_payments
response = await AbonentPays.async_request(
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 537, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/config/custom_components/lkcomu_interrao/_base.py", line 506, in async_update
await with_auto_auth(self._account.api, self.async_update_internal)
File "/config/custom_components/lkcomu_interrao/_util.py", line 156, in with_auto_auth
return await async_getter(*args, **kwargs)
File "/config/custom_components/lkcomu_interrao/binary_sensor.py", line 82, in async_update_internal
self._last_payment = await self._account.async_get_last_payment()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 1155, in async_get_last_payment
return await self._internal_async_find_dated_last(self.async_get_payments, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 140, in _internal_async_find_dated_last
all_items = await async_getter(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 164, in async_get_payments
return await self.async_get_smorodina_payments(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 149, in async_get_smorodina_payments
response = await AbonentPays.async_request(
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 537, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')
2022-10-10 19:09:41.853 ERROR (MainThread) [homeassistant.components.sensor] lkcomu_interrao: Error on device update!
Traceback (most recent call last):
File "/config/custom_components/lkcomu_interrao/_util.py", line 153, in with_auto_auth
return await async_getter(*args, **kwargs)
File "/config/custom_components/lkcomu_interrao/sensor.py", line 924, in async_update_internal
self._last_invoice = await self._account.async_get_last_invoice()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 1232, in async_get_last_invoice
return await self._internal_async_find_dated_last(self.async_get_invoices, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 140, in _internal_async_find_dated_last
all_items = await async_getter(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 504, in async_get_invoices
return await self.async_get_smorodina_invoices(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 511, in async_get_smorodina_invoices
response = await AbonentChargeDetail.async_request(
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 655, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/config/custom_components/lkcomu_interrao/_base.py", line 506, in async_update
await with_auto_auth(self._account.api, self.async_update_internal)
File "/config/custom_components/lkcomu_interrao/_util.py", line 156, in with_auto_auth
return await async_getter(*args, **kwargs)
File "/config/custom_components/lkcomu_interrao/sensor.py", line 924, in async_update_internal
self._last_invoice = await self._account.async_get_last_invoice()
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 1232, in async_get_last_invoice
return await self._internal_async_find_dated_last(self.async_get_invoices, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 140, in _internal_async_find_dated_last
all_items = await async_getter(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 504, in async_get_invoices
return await self.async_get_smorodina_invoices(start, end)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 511, in async_get_smorodina_invoices
response = await AbonentChargeDetail.async_request(
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 655, in async_request
return await api.async_action_map(cls, ACTION_SQL, proxy, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 595, in async_action_map
response = await self._async_action_with_exceptions(action, query, data)
File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 577, in _async_action_with_exceptions
raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')`

**Comment by Sashik259** [comment]
Works again
