### ISSUE TITLE
Не работает интеграция после обновления ядра на 2023.5.4

### ISSUE THREAD

**Issue by logistik777** [alryaz/hass-lkcomu-interrao#31]
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 1
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.config_entries
Source: custom_components/lkcomu_interrao/__init__.py:272
Integration: Личный кабинет Интер РАО (Энергосбыт) (documentation, issues)
First occurred: 10:58:44 (1 occurrences)
Last logged: 10:58:44

Error setting up entry my.mosenergosbyt.ru (+7916xxxxxxx) for lkcomu_interrao
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lkcomu_interrao/__init__.py", line 272, in async_setup_entry
    await api_object.async_authenticate()
  File "/usr/local/lib/python3.10/site-packages/inter_rao_energosbyt/interfaces.py", line 612, in async_authenticate
    async with self._session.get(self.AUTH_URL) as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

**Comment by AlexObukhoff** [comment]
Аналогично не работает в версии 2024.5.3

`Connection reset by peer` - а не вызвано ли это падение изменениями на стороне mosenergosbyt?
