### ISSUE TITLE
Не понятные ошибки в логе

### ISSUE THREAD

**Issue by MaximSN** [alryaz/hass-lkcomu-interrao#6]
Вижу в логе непонятные ошибки. После перезагрузки значения всех сенсоров недоступно
Logger: homeassistant.components.sensor
Source: custom_components/lkcomu_interrao/sensor.py:382
Integration: Сенсор (documentation, issues)
First occurred: 20:29:07 (2 occurrences)
Last logged: 20:33:29

lkcomu_interrao: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/lkcomu_interrao/_util.py", line 153, in with_auto_auth
    return await async_getter(*args, **kwargs)
  File "/config/custom_components/lkcomu_interrao/sensor.py", line 382, in async_update_internal
    self._balance = await account.async_get_balance()
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 591, in async_get_balance
    response_balance = await AbonentCurrentBalance.async_request(self.api, proxy, provider)
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 265, in async_request
    return await api.async_action_map(cls, ACTION_SQL, proxy, data)
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/interfaces.py", line 592, in async_action_map
    response = await self._async_action_with_exceptions(action, query, data)
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/interfaces.py", line 574, in _async_action_with_exceptions
    raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/config/custom_components/lkcomu_interrao/_base.py", line 564, in async_update
    await with_auto_auth(self._account.api, self.async_update_internal)
  File "/config/custom_components/lkcomu_interrao/_util.py", line 156, in with_auto_auth
    return await async_getter(*args, **kwargs)
  File "/config/custom_components/lkcomu_interrao/sensor.py", line 382, in async_update_internal
    self._balance = await account.async_get_balance()
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/presets/smorodina.py", line 591, in async_get_balance
    response_balance = await AbonentCurrentBalance.async_request(self.api, proxy, provider)
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/actions/sql/abonent.py", line 265, in async_request
    return await api.async_action_map(cls, ACTION_SQL, proxy, data)
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/interfaces.py", line 592, in async_action_map
    response = await self._async_action_with_exceptions(action, query, data)
  File "/usr/local/lib/python3.8/site-packages/inter_rao_energosbyt/interfaces.py", line 574, in _async_action_with_exceptions
    raise EnergosbytException("ActionRequest error", error_code, error_text)
inter_rao_energosbyt.exceptions.EnergosbytException: ('ActionRequest error', 300, 'connect timed out (<no description provided>)')

**Comment by MaximSN** [comment]
Оказывается это сам сервер Мосэнергосбыта не доступен. В личном кабинете тоже ошибки

**Comment by alryaz** [comment]
Такое бывает, но сглаживать это, к сожалению, неизвестно, как.
Это особенно ощутимо с Томскими кабинетами, где ответы могут приходить минутами.
ТКО-шные вообще в пролёте в последнее время (мой опыт, могу ошибаться).
